### ISSUE TITLE
CMAKE_C_COMPILER not set

### ISSUE THREAD

**Issue by ali-abbas-10p** [faircoin/fairbread-android#1]
Hey,

I am trying to build this project and i am getting error shown below.
Can please anyone help how to fix this issue?

> Build command failed.
> 
> 
> Error while executing process /media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/media/ali/Softwares/Projects/crypto/fairbread-android/app -B/media/ali/Softwares/Projects/crypto/fairbread-android/app/.externalNativeBuild/cmake/brdDebug/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/ali/Softwares/Projects/crypto/fairbread-android/app/build/intermediates/cmake/brd/debug/obj/x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/media/ali/Softwares/Tools/sdk/ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=0 -DBITCOIN_DEBUG=1 -DCMAKE_TOOLCHAIN_FILE=/media/ali/Softwares/Tools/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}
> 
> 
>  (include)   CMakeLists.txt 
> Open File
> 
> 
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> 
> 
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> 
> 
> -- Configuring incomplete, errors occurred!
> 
> 
> Build command failed.
> 
> 
> Error while executing process /media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/media/ali/Softwares/Projects/crypto/fairbread-android/app -B/media/ali/Softwares/Projects/crypto/fairbread-android/app/.externalNativeBuild/cmake/brdTestnetRelease/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/ali/Softwares/Projects/crypto/fairbread-android/app/build/intermediates/cmake/brdTestnet/release/obj/x86_64 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/media/ali/Softwares/Tools/sdk/ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=1 -DCMAKE_TOOLCHAIN_FILE=/media/ali/Softwares/Tools/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}
> 
> 
>  (include)   CMakeLists.txt 
> Open File
> 
> 
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> 
> 
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> 
> 
> -- Configuring incomplete, errors occurred!
> 
> 
> Build command failed.
> 
> 
> Error while executing process /media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/media/ali/Softwares/Projects/crypto/fairbread-android/app -B/media/ali/Softwares/Projects/crypto/fairbread-android/app/.externalNativeBuild/cmake/brdRelease/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/ali/Softwares/Projects/crypto/fairbread-android/app/build/intermediates/cmake/brd/release/obj/x86_64 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/media/ali/Softwares/Tools/sdk/ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=0 -DCMAKE_TOOLCHAIN_FILE=/media/ali/Softwares/Tools/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}
> 
> 
>  (include)   CMakeLists.txt 
> Open File
> 
> 
> -- Configuring incomplete, errors occurred!
> 
> 
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> 
> 
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> 
> 
> Build command failed.
> 
> 
> Error while executing process /media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/media/ali/Softwares/Projects/crypto/fairbread-android/app -B/media/ali/Softwares/Projects/crypto/fairbread-android/app/.externalNativeBuild/cmake/brdTestnetDebug/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/ali/Softwares/Projects/crypto/fairbread-android/app/build/intermediates/cmake/brdTestnet/debug/obj/x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/media/ali/Softwares/Tools/sdk/ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=1 -DBITCOIN_DEBUG=1 -DCMAKE_TOOLCHAIN_FILE=/media/ali/Softwares/Tools/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/media/ali/Softwares/Tools/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}
> 
> 
>  (include)   CMakeLists.txt 
> Open File
> 
> 
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> 
> 
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> 
> 
> -- Configuring incomplete, errors occurred!

**Comment by thokon00** [comment]
No code has been committed to this repo so far. It's basically even with upstream master. Please wait until there is actually development here before you file issues. If you have problems building breadwallet-android consult the upstream team.
